### ISSUE TITLE
Slack建てたい？

### ISSUE THREAD

**Issue by b1u3-YumaNoguchi** [b1u3-YumaNoguchi/TeamEngineering#2]
Slack建ててそっちでチャットする？

**Comment by TstsuyaSakai** [comment]
Slackっての初めて聞いたんだけどいい経験だしそっちでもいいよ

**Comment by b1u3-YumaNoguchi** [comment]
@TstsuyaSakai 
中期のインターン行ったときにSlackとgithub両方使ってた。SlackはLineみたいなやつ。チャットボットとかできるらしい。

**Comment by TstsuyaSakai** [comment]
見てみた。とりあえず使ってみましょーか

**Comment by b1u3-YumaNoguchi** [comment]
了解
