### ISSUE TITLE
ワークフローを考える

### ISSUE THREAD

**Issue by b1u3-YumaNoguchi** [b1u3-YumaNoguchi/TeamEngineering#4]
修正、改善のプルリクを送るまでのことを考える。

**Comment by TstsuyaSakai** [comment]
https://qiita.com/Commander-Aipa/items/d61d21988a36a4d0e58b
この手順踏めば出来そうだけど、プルリクまでのワークフローって具体的にどう表現すれば良いんかな？

**Comment by b1u3-YumaNoguchi** [comment]
インターン先ではひとつのファイルで、コマンド直書きしてた。
Markdownでコード表現

```
%git clone hogehoge
```

的な

**Comment by TstsuyaSakai** [comment]
了解
