### ISSUE TITLE
README.mdでプルリクを出してみてほしい

### ISSUE THREAD

**Issue by b1u3-YumaNoguchi** [b1u3-YumaNoguchi/TeamEngineering#5]
README.mdに変更を加えてプルリクしてほしい。
流れ的には
①ブランチをつくる
②pushをする
③プルリク出す
みたいな？
ブランチ名はなんでもいい。
とりあえず僕がマージしてみたい

**Comment by TstsuyaSakai** [comment]
ん、何も変更加えないでプルリク出しちゃったけど送れてはいるかな？

**Comment by b1u3-YumaNoguchi** [comment]
OK！！ できれば加えてほしかったけどw 
ついでに変更したからpullして確認してみて。あと、適当に自分ルール的なの追加してって。みんながいい感じにできそうな案。
