### ISSUE TITLE
Slackをたてる

### ISSUE THREAD

**Issue by b1u3-YumaNoguchi** [b1u3-YumaNoguchi/TeamEngineering#6]
Slackの立て方とか調べて、立てる

**Comment by TstsuyaSakai** [comment]
https://join.slack.com/t/git-practice/shared_invite/enQtNDYwMTYwNDE5NjY0LTQxNjliMWVkZDg1YTIyN2M3ZmM5OGJjMTg0ODkwYzVlZTMxMTU1ZGY2ZThlMjVmMzUwYTU5N2RkYjVhZTM5YTM
立ててみた。こんな感じ？

**Comment by b1u3-YumaNoguchi** [comment]
@TstsuyaSakai 
おっけい。多分大丈夫！！！
閉じます！！
